### ISSUE TITLE
obj_weight in hprod

### ISSUE THREAD

**Issue by tcovert** [JuliaSmoothOptimizers/ManualNLPModels.jl#19]
The example given in the documentation shows a function which (a) computes the hessian-vector product, (b) stores it in the passed `hv` vector, and (c) *returns* the product of the hessian-vector product with the optional parameter `obj_weight`.  That is, the function's return value is not the same as what it stores in the passed vector `hv` if `obj_weight` is not equal to one. 

Is this intentional?  Should I be writing `hprod` functions which store the hessian-vector product in their passed variable but return the product of that with the objective weight?  Or is an oversight in the documentation, and I should be storing `hv * obj_weight` in the passed vector?

Thanks in advance.

**Comment by abelsiqueira** [comment]
Hi @tcovert, that is an oversight, thanks for catching it! You want to store `hv * obj_weight`.
Do you want to make a PR fixing this? Otherwise we'll fix it soon.

**Comment by abelsiqueira** [comment]
Thanks for the issue, it should be updated online soon after the 0.1.5 version is merged.
